### ISSUE TITLE
Can't find output dir folder

### ISSUE THREAD

**Issue by ShulkMaster** [hdoc/hdoc#10]
Currently I have this setup in the `.hdoc.toml` file

```
[project]
name = "Simulation"
version = "1.0.0"
git_repo_url = "https://github.com/ShulkMaster/Simu_01-2022/tree/master/"

[paths]
compile_commands = "build/compile_commands.json"
output_dir = "docs"
```

When use the `hdoc  -v` command all the outputs looks ok, it detects everything and even shows the message ' Documentation uploaded successfully' however I wish to use a self hosted version of the documentation but in the directory I cant find the `docs`   folder anywhere.

I checked the documentation and can't find any obvious way of doing so such a a command line arg or something, Is there any step I'm missing?

the setup is windows OS but the commands are run through WSL2 on Ubuntu distro 20.04 and the binary I got it from the official website by creating my account

Here's is my publish doc so you can see It works but I can't get the static files i need to host it.

[My documentation](https://docs.hdoc.io/00088116/simu/f0C7B438F45630980.html)

**Comment by hdoc** [comment]
Hello!

The precompiled binaries hosted on our website can only upload documentation to docs.hdoc.io. They cannot save documentation to the local filesystem. To be able to output documentation to your filesystem you must compile your own copy of hdoc using the code in this repository. There are instructions in the README for compiling hdoc which should work on your WSL setup.

We apologize for the inconvenience and thank you for your feedback. This is definitely something where we could improve hdoc and indicate that the precompiled binaries cannot output documentation to disk when the `output_dir` option is specified in .hdoc.toml.

**Comment by ShulkMaster** [comment]
Thank you very much 🤗

**Comment by hdoc** [comment]
Hello, this bug has been fixed in the latest version of hdoc. Now, users are notified if their documentation will not be saved locally if they mistakenly use the `output_dir` configuration option. In addition, we've [updated hdoc's documentation](https://hdoc.io/docs/reference/config-file-reference/#output-dir) to reflect that this configuration option is not always required. We have included your name in the [release notes](https://hdoc.io/release-notes/#version-1-2-2-17-march-2022) as a token of appreciation for reporting this bug. Thank you!
