### ISSUE TITLE
Search page links to wrong anchor id

### ISSUE THREAD

**Issue by jtbandes** [hdoc/hdoc#14]
**Steps to reproduce:**
- Visit https://mcap.dev/docs/cpp/search.html
- Search for `filereader`
- Click the constructor (2nd search result)

**Expected behavior:**
Link goes to https://mcap.dev/docs/cpp/r703E2A4BE14D967D.html#F328627266D029A6

**Actual behavior:**
Link goes to https://mcap.dev/docs/cpp/r703E2A4BE14D967D.html#F328627266D029A6.html

**Comment by hdoc** [comment]
Thank you for the issue report @jtbandes, we appreciate you supplying us with detailed instructions. We've identified where the bug is and we have a fix in our internal repo, but we will wait for the next release to ship it out. We want to bundle in a few larger changes together instead of shipping out small point-release fixes. Expect a fix in the coming weeks.

**Comment by hdoc** [comment]
Hello @jtbandes, this issue has been fixed in hdoc 1.3.0, which was just released. As always, thank you for your detailed reproduction steps and your continued help in making hdoc a better tool. We have credited you in the release notes, which can be found here: https://hdoc.io/release-notes/#version-1-3-0-21-july-2022. 

If there are any other issues or suggestions you have for hdoc please let us know, your feedback has been great!
