### ISSUE TITLE
Ability to hide timestamp in generated output

### ISSUE THREAD

**Issue by jtbandes** [hdoc/hdoc#18]
This is a minor request, but one small change in my [hdoc patches](https://github.com/foxglove/mcap/blob/a85bd00295255b134f3083efbc5d2274294a83df/cpp/hdoc.patch) is to hide the timestamp from the footer of generated docs:

<img width="583" alt="image" src="https://user-images.githubusercontent.com/14237/180505343-ed737c7d-06fb-41ea-88fe-8a8835a084a1.png">

Removing the timestamp reduces unnecessary thrash in the generated output. For example, [this docs update](https://github.com/foxglove/mcap/commit/1e76556a0c0a0f002a9e80ff7ef9f07c153db28b) does **not** include any changes to cpp docs because the timestamp is not in the footer.

**Comment by hdoc** [comment]
We won't be implementing this in hdoc, at least not at this time. The inclusion of the timestamp is a useful feature for our hosted offering, letting creators know when the documentation was generated and acting as an important indicator of the "freshness" of their docs. I understand that it is inconvenient for your system, but checking in generated HTML documentation into the source tree is unconventional from our point of view and changes to make this more convenient are not going to be prioritized. 

We would be happy to reconsider this if the rationale for removing it becomes stronger in the future.

**Comment by jtbandes** [comment]
Would you be interested in reviewing a PR to implement it?

**Comment by hdoc** [comment]
Thank you for your offer of submitting a PR but we won't accept PRs on this topic because the justification for this is not strong enough. As before, we would be happy to reconsider this in the future. 

Unfortunately we're going to have to ask you to keep carrying that patch locally, at least it isn't too hefty.

**Comment by glencairn** [comment]
> checking in generated HTML documentation into the source tree is unconventional

I generally agree, but what if a project wants to host their docs using GitHub Pages?

> The inclusion of the timestamp is a useful feature for our hosted offering, letting creators know when the documentation was generated and acting as an important indicator of the "freshness" of their docs.

It is a nice feature but, In my opinion, including the timestamp in the generated HTML should be configurable. This seems like a big loss for such a trivial addition to the `.hdoc.toml` file.

**Comment by hdoc** [comment]
> > checking in generated HTML documentation into the source tree is unconventional
> 
> I generally agree, but what if a project wants to host their docs using GitHub Pages?

My understanding is that GitHub pages typically uses a [separate branch as the source](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) of the HTML docs. Users who use GitHub Pages would commit their docs to this separate branch and update the branch when they update their docs. Yes, it's not ideal that all of the hdoc-generated HTML files will have a 1 line change in the footer to update the date, but the presence of a timestamp doesn't stop anyone from taking this path. Users who really want to avoid this can carry a one-line patch (like @jtbandes [does here](https://github.com/foxglove/mcap/blob/3a2c55348ca6a55cbe1d91ca27b1afc3d5efe2b0/cpp/hdoc.patch#L41-L42)) to remove the date from the footer.

> 
> > The inclusion of the timestamp is a useful feature for our hosted offering, letting creators know when the documentation was generated and acting as an important indicator of the "freshness" of their docs.
> 
> It is a nice feature but, In my opinion, including the timestamp in the generated HTML should be configurable. This seems like a big loss for such a trivial addition to the `.hdoc.toml` file.

I understand that it's frustrating that this feature is being left out. Please allow me to provide some perspective from our side:

1. The line on what's configurable and what's not has to be drawn somewhere, and we're drawing it here because:
    - We like having the date in the footer
    - It is useful, because it indicates the freshness of the docs
    - Its presence does not preclude users with other tastes from using hdoc, it merely makes it slightly less convenient
    - Users who have other tastes can make a one-line patch to change the behavior if they so desire
3. Why do we have this stance? We pride ourselves on having only [12 configuration parameters](https://hdoc.io/docs/reference/config-file-reference/). Ideally, there would be zero, but until then we have to be judicious in what new configuration parameters, if any, we add. If we say "yes" to every request, we will end up like Doxygen, with [289 configuration parameters](https://www.doxygen.nl/manual/config.html) by my count. Yes, the configurability is nice, but it comes at the cost of an explosion in the number of permutations that need to be tested and validated. Furthermore, there is a cognitive cost that users have to bear to use the software. 
4. Our philosophy is to minimize the number configuration parameters and users who think differently are welcome to patch hdoc to meet their needs.
5. Other software, namely Doxygen, includes this functionality too:
<img width="567" alt="doxygen-date-footer" src="https://user-images.githubusercontent.com/68132204/189791364-059c7c96-50db-474f-ab37-3e6bccf8803e.png">

I apologize for not implementing your feature request. I hope my explanation above provides some insight into why we're doing this. Of course, we will keep an open mind and we will be happy to reconsider this if you have some other information or concrete usecase that justifies it. Unfortunately, reducing the thrash for users who choose to commit their generated HTML into git is not currently one of those usecases.
