### ISSUE TITLE
Compile error on Ubuntu

### ISSUE THREAD

**Issue by yqs112358** [hdoc/hdoc#8]
When followed the command in #2 to install depends and execute `meson build & ninja -C build`, error occur when compiling main.cpp
```
[62/95] Compiling C++ object 'hdoc@exe/src_main.cpp.o'.
FAILED: hdoc@exe/src_main.cpp.o
c++ -Ihdoc@exe -I. -I.. -I../src -I../subprojects/cmark-gfm/src -I../subprojects/cmark-gfm/extensions -I../subprojects/spdlog/include -I../subprojects/tiny-process-library/tpl -Isubprojects/ctml -I../subprojects/ctml -Isubprojects/argparse -I../subprojects/argparse -Isubprojects/toml++ -I../subprojects/toml++ -Isubprojects/doctest -I../subprojects/doctest -I../subprojects/cereal/include -Isubprojects/cpp-httplib -I../subprojects/cpp-httplib -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -g -fno-rtti -DCPPHTTPLIB_OPENSSL_SUPPORT -pthread -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -isystem/usr/lib/llvm-10/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -MD -MQ 'hdoc@exe/src_main.cpp.o' -MF 'hdoc@exe/src_main.cpp.o.d' -o 'hdoc@exe/src_main.cpp.o' -c ../src/main.cpp
../src/main.cpp: In function ‘int main(int, char**)’:
../src/main.cpp:24:72: error: too many arguments to function ‘unsigned int llvm::hardware_concurrency()’
   24 |   llvm::ThreadPool       pool(llvm::hardware_concurrency(cfg.numThreads));
      |                                                                        ^
In file included from ../src/main.cpp:6:
/usr/include/llvm-10/llvm/Support/Threading.h:159:12: note: declared here
  159 |   unsigned hardware_concurrency();
      |            ^~~~~~~~~~~~~~~~~~~~
[71/95] Compiling C++ object 'hdoc@sta/src_indexer_Indexer.cpp.o'.
ninja: build stopped: subcommand failed.
```
<img width="435" alt="image" src="https://user-images.githubusercontent.com/37969157/156864281-7b1730b5-8637-4708-8acc-fd81e3265137.png">

This problem is reported in `client-main.cpp:` and `main.cpp`
**When i delete this  parameter `cfg.numThreads`, then the compile finished well.**
So will this modification cause problem in production environment? or it is just ok?

**Comment by hdoc** [comment]
Hello, happy to see that the error in your previous issue has been solved :)

This seems to be due your use of an old version of LLVM (apparently LLVM 10 based on the snippet you posted?). [This change in LLVM](https://github.com/llvm/llvm-project/commit/8404aeb56a73ab24f9b295111de3b37a37f0b841#diff-3a7935893f5ff6fb468296962078a2978752378bc97706c1f990729947d9134fR188) added the `numThreads` parameter to `llvm::hardware_concurrency()`. hdoc [was updated in release 1.1.0](https://github.com/hdoc/hdoc/commit/882d519de12e3d207aaac7a3bac148557bfb784b#diff-0f500e742e83eec63c4cb3c4aea2bc6a409932ae91c4d3cf653cd771a32c8f83L20) to use the new function signature.

To answer your question: deleting the parameter will work and will default to using all of the threads that your machine has available. You can also specify the number of threads you would like hdoc to use instead of passing in the result of `llvm::hardware_concurrency()` if you do not wish for hdoc to use all of the threads that are available.

We would be curious to hear about your use of hdoc in a production environment. Feel free to contact us at [contact@hdoc.io](mailto:contact@hdoc.io).
